logging:
  config: classpath:logback.xml

server:
  port: 8080
  tomcat:
    max-threads: 10
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
      minimum-idle: 2
      # logs WARN with stacktrace if connection is held for more than 30 seconds
      # leakDetectionThreshold: 30000
  jpa:
    open-in-view: false
    # show-sql: true

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus